PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdfsplus: <http://topbraid.org/spin/rdfsplus#>
PREFIX archi: <http://ikm-group.ch/archiMEO/archimate#>
PREFIX terra: <http://archimateiac.raphaelhackenso.at/TerraformOntology#>
PREFIX archimateiac: <http://archimateiac.raphaelhackenso.at/ArchiMateIaCOntology#>

# Select the terraform class for a given ArchiMate class
SELECT ?terraformClass
WHERE {
  archi:ApplicationCollaboration rdfs:subClassOf [
    rdf:type owl:Restriction ;
    owl:onProperty archimateiac:semanticallyAnnotatedAs ;
    owl:someValuesFrom ?terraformClass
  ] .
}

# Select the other required terraform classes
SELECT DISTINCT ?terraformClass ?cardinality
WHERE {
  terra:azurerm_linux_virtual_machine a owl:Class .
  terra:azurerm_linux_virtual_machine rdfs:subClassOf ?restriction .
  ?restriction owl:onProperty archimateiac:requiresOtherTerraformResource ;
               owl:qualifiedCardinality ?cardinality ;
  				owl:onClass ?terraformClass
}
